# docker-compose.yml
version: '3.3'
services:
  dagent:
    restart: always
    image: golang_dagent
    volumes:
      - /tmp/air_result.json:/tmp/air_result.json
      - /etc/pos:/etc/pos
    network_mode: "host"
    expose:
      - 3000
      - 18716
    ports:
      - 3000:3000
    container_name: dagent
    environment:
      - DAGENT_HOST=localhost
  flask:
    restart: always
    image: python_mtool
    network_mode: "host"
    ports:
      - 5000:5000
    container_name: mtool
    environment:
      - DAGENT_HOST=localhost
      - INFLUX_HOST=0.0.0.0
      - INFLUXDB_URL=http://0.0.0.0:8086
      - KAPACITOR_URL=http://0.0.0.0:9092
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    depends_on: ['influxdb','kapacitor']
  nginx:
    restart: always
    image: nginx_ui
    container_name: nginx
    ports:
      - 80:80
    depends_on: ['influxdb','kapacitor','flask']
    network_mode: "host"
