
name: Image_Upload

on:
   push:
      branches:
         - main
   workflow_dispatch:
      inputs:
         logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
         tags:
            description: 'Test scenario tags'

env:
  REGISTRY: ghcr.io

jobs:
  Upload_Package:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: package build
      working-directory: ${{github.workspace}}
      run: |
        sudo apt update
        sudo ./script/build_docker.sh

    - name: Log in to Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Tag Docker Image
      run: |
        sudo docker tag golang_dagent ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/golang_dagent
        sudo docker tag python_mtool ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/python_mtool
        sudo docker tag nginx_ui ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/nginx_ui

    - name: Push Docker Image
      run: |
        sudo docker push ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/golang_dagent
        sudo docker push ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/python_mtool
        sudo docker push ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/nginx_ui
